"""
Dynamic Module Loader for TerraScout AI
Lazy-loads modules on demand to reduce startup time from 15-20s to 2-3s
"""

import importlib
import sys
from typing import Callable, Optional, Dict
import streamlit as st

# Cache for loaded render functions
_render_function_cache: Dict[str, Callable] = {}

# Special cases: modules whose render function names don't follow the standard pattern
# Standard pattern: render_{module_id}_tab
# These modules use different naming conventions (most use _maps_tab suffix)
CUSTOM_FUNCTION_NAMES = {
    "agriculture": "render_agriculture_maps_tab",
    "api_health": "render_api_health_dashboard_tab",
    "airport": "render_airport_maps_tab",
    "amusement": "render_amusement_maps_tab",
    "ancient": "render_ancient_maps_tab",
    "ancient_weapons": "render_ancient_weapons_maps_tab",
    "architecture": "render_architecture_maps_tab",
    "astronomy": "render_astronomy_maps_tab",
    "bamboo": "render_bamboo_maps_tab",
    "beer": "render_beer_maps_tab",
    "biodiv_global": "render_biodiversity_global_maps_tab",
    "biogeography": "render_biogeography_maps_tab",
    "borders": "render_borders_conflicts_maps_tab",
    "botanical": "render_botanical_maps_tab",
    "bread": "render_bread_maps_tab",
    "bridge": "render_bridge_maps_tab",
    "calendar": "render_calendar_maps_tab",
    "calligraphy": "render_calligraphy_maps_tab",
    "candy": "render_candy_maps_tab",
    "carnival": "render_carnival_maps_tab",
    "caves": "render_cave_maps_tab",
    "cemetery": "render_cemetery_maps_tab",
    "cheese": "render_cheese_maps_tab",
    "chocolate": "render_chocolate_maps_tab",
    "cinema": "render_cinema_maps_tab",
    "circus": "render_circus_maps_tab",
    "civilization": "render_civilization_maps_tab",
    "climate": "render_climate_monitor_tab",
    "climate_history": "render_climate_history_maps_tab",
    "clock": "render_clock_maps_tab",
    "coffee": "render_coffee_maps_tab",
    "coin": "render_coin_maps_tab",
    "composite": "render_composite_maps_tab",
    "conspiracy": "render_conspiracy_maps_tab",
    "coral_reef": "render_coral_reef_maps_tab",
    "corn": "render_corn_maps_tab",
    "cost_living": "render_cost_living_maps_tab",
    "cotton": "render_cotton_maps_tab",
    "crime_safety": "render_crime_safety_maps_tab",
    "cryptid": "render_cryptid_maps_tab",
    "crypto": "render_crypto_maps_tab",
    "cuisine": "render_cuisine_maps_tab",
    "dance": "render_dance_maps_tab",
    "deep_analysis": "render_deep_zone_analysis_tab",
    "demographics": "render_world_demographics_tab",
    "global_dashboard": "render_global_dashboard_realtime_tab",
    "global_realtime": "render_global_realtime_tab",
    "deserts": "render_desert_maps_tab",
    "dinosaur": "render_dinosaur_maps_tab",
    "disaster": "render_disaster_maps_tab",
    "dragon": "render_dragon_maps_tab",
    "economics": "render_economics_maps_tab",
    "education": "render_education_maps_tab",
    "empires": "render_empires_maps_tab",
    "energy": "render_energy_explorer_tab",
    "exploration": "render_exploration_maps_tab",
    "extreme_geo": "render_extreme_geography_tab",
    "fashion": "render_fashion_maps_tab",
    "festival": "render_festival_maps_tab",
    "fjords": "render_fjord_maps_tab",
    "fortress": "render_fortress_maps_tab",
    "games": "render_games_maps_tab",
    "garden": "render_garden_maps_tab",
    "gastronomy": "render_gastronomy_maps_tab",
    "gemstone": "render_gemstone_maps_tab",
    "genetics": "render_genetics_maps_tab",
    "glaciers": "render_glacier_maps_tab",
    "glass": "render_glass_maps_tab",
    "haunted": "render_haunted_maps_tab",
    "hidden_structures": "render_hidden_structures_maps_tab",
    "historical": "render_historical_maps_tab",
    "honey": "render_honey_maps_tab",
    "horse": "render_horse_maps_tab",
    "ice_cream": "render_ice_cream_maps_tab",
    "indigenous": "render_indigenous_maps_tab",
    "instrument": "render_instrument_maps_tab",
    "islands": "render_island_maps_tab",
    "isolated_buildings": "render_isolated_buildings_maps_tab",
    "jewelry": "render_jewelry_maps_tab",
    "landuse": "render_landuse_explorer_tab",
    "language": "render_language_maps_tab",
    "library": "render_library_maps_tab",
    "lighthouse": "render_lighthouse_maps_tab",
    "linguistic": "render_linguistic_maps_tab",
    "literature": "render_literature_maps_tab",
    "map_catalog": "render_catalog_tab",
    "marathon": "render_marathon_maps_tab",
    "maritime": "render_maritime_maps_tab",
    "market": "render_market_maps_tab",
    "martial_arts": "render_martial_arts_maps_tab",
    "mask": "render_mask_maps_tab",
    "medical": "render_medical_maps_tab",
    "medieval": "render_medieval_maps_tab",
    "migration": "render_migration_maps_tab",
    "military": "render_military_maps_tab",
    "mining": "render_mining_maps_tab",
    "mountains": "render_mountain_maps_tab",
    "museum": "render_museum_maps_tab",
    "music_culture": "render_music_culture_maps_tab",
    "myth_locations": "render_myth_locations_maps_tab",
    "mythology": "render_mythology_maps_tab",
    "mythology_deep": "render_mythology_deep_maps_tab",
    "nuclear": "render_nuclear_maps_tab",
    "ocean": "render_ocean_explorer_tab",
    "osm_explorer": "render_osm_explorer",
    "olive": "render_olive_maps_tab",
    "open_buildings": "render_open_buildings_explorer_tab",
    "opera": "render_opera_maps_tab",
    "origami": "render_origami_maps_tab",
    "pandemic": "render_pandemic_maps_tab",
    "paranormal": "render_paranormal_maps_tab",
    "pasta": "render_pasta_maps_tab",
    "perfume": "render_perfume_maps_tab",
    "photography": "render_photography_maps_tab",
    "pilgrimage": "render_pilgrimage_maps_tab",
    "pirate": "render_pirate_maps_tab",
    "pollution": "render_pollution_maps_tab",
    "population": "render_population_maps_tab",
    "potato": "render_potato_maps_tab",
    "pottery": "render_pottery_maps_tab",
    "prison": "render_prison_maps_tab",
    "railway": "render_railway_maps_tab",
    "realtime": "render_realtime_dashboard_tab",
    "religion": "render_religion_maps_tab",
    "renewable": "render_renewable_maps_tab",
    "rice": "render_rice_maps_tab",
    "robot": "render_robot_maps_tab",
    "ruins": "render_ruins_maps_tab",
    "salt": "render_salt_maps_tab",
    "sculpture": "render_sculpture_maps_tab",
    "shipwreck": "render_shipwreck_maps_tab",
    "silk_road": "render_silk_road_maps_tab",
    "skyscraper": "render_skyscraper_maps_tab",
    "soil": "render_soil_explorer_tab",
    "soy": "render_soy_maps_tab",
    "spa": "render_spa_maps_tab",
    "space": "render_space_maps_tab",
    "spice": "render_spice_maps_tab",
    "sports": "render_sports_maps_tab",
    "street_art": "render_street_art_maps_tab",
    "street_food": "render_street_food_maps_tab",
    "submarine": "render_submarine_maps_tab",
    "tattoo": "render_tattoo_maps_tab",
    "tea": "render_tea_maps_tab",
    "technology": "render_technology_maps_tab",
    "telescope": "render_telescope_maps_tab",
    "textile": "render_textile_maps_tab",
    "thematic": "render_thematic_maps_tab",
    "toy": "render_toy_maps_tab",
    "trad_med": "render_trad_medicine_maps_tab",
    "trade_routes": "render_trade_routes_maps_tab",
    "train_journey": "render_train_journey_maps_tab",
    "transport": "render_transport_maps_tab",
    "treasure": "render_treasure_maps_tab",
    "underwater": "render_underwater_maps_tab",
    "unesco": "render_unesco_maps_tab",
    "urban": "render_urban_analytics_tab",
    "volcano_deep": "render_volcano_deep_maps_tab",
    "volcano_live": "render_volcano_live_maps_tab",
    "volcanoes": "render_volcano_maps_tab",
    "water": "render_water_explorer_tab",
    "waterfalls": "render_waterfall_maps_tab",
    "waterpark": "render_waterpark_maps_tab",
    "waterways": "render_waterway_maps_tab",
    "wheat": "render_wheat_maps_tab",
    "wildfires": "render_fire_tracker_tab",
    "wine": "render_wine_maps_tab",
    "world_data": "render_world_data_maps_tab",
    "writing": "render_writing_maps_tab",
    "zodiac": "render_zodiac_maps_tab",
    "zone_intel": "render_zone_intelligence_tab",
    "compare_locations": "render_compare_locations_tab",
    "route_analysis": "render_route_analysis_tab",
    "predictive_risk": "render_predictive_risk_tab",
    "timeline": "render_timeline_analysis_tab",
    "night_vision": "render_night_vision_tab",
    "terrain_3d": "render_terrain_3d_tab",
    "report_gen": "render_report_generator_tab",
    "ocean_proximity": "render_ocean_proximity_tab",
    "climate_zone": "render_climate_zone_tab",
    "scenario_simulator": "render_scenario_simulator_tab",
    "mining_suitability": "render_mining_suitability_tab",
    "ai_scoring": "render_ai_scoring_tab",
    "smart_insights": "render_smart_insights_tab",
    "environmental_dna": "render_environmental_dna_tab",
    "suitability_analyzer": "render_suitability_analyzer_tab",
    "anomaly_detector": "render_anomaly_detector_tab",
    "threat_matrix": "render_threat_matrix_tab",
    "pattern_recognizer": "render_pattern_recognizer_tab",
    "mission_planner": "render_mission_planner_tab",
    "correlation_engine": "render_correlation_engine_tab",
    "change_detector": "render_change_detector_tab",
    "strategic_report": "render_strategic_report_tab",
    "terrain_classifier": "render_terrain_classifier_tab",
    "water_intelligence": "render_water_intelligence_tab",
    "geo_profiler": "render_geo_profiler_tab",
    "site_ranker": "render_site_ranker_tab",
    "network_analysis": "render_network_analysis_tab",
    "multi_hazard": "render_multi_hazard_tab",
    "data_fusion": "render_data_fusion_tab",
    "climate_dashboard": "render_climate_dashboard_tab",
    "resource_scanner": "render_resource_scanner_tab",
    "infra_density": "render_population_density_tab",
    "ecosystem_health": "render_ecosystem_health_tab",
    "land_capability": "render_land_capability_tab",
    "accessibility_mapper": "render_accessibility_mapper_tab",
    "climate_risk_ai": "render_climate_risk_tab",
    "resource_potential": "render_resource_potential_tab",
    "habitat_analyzer": "render_habitat_analyzer_tab",
    "soil_intelligence": "render_soil_intelligence_tab",
    "microclimate_ai": "render_microclimate_tab",
    "environmental_score": "render_environmental_score_tab",
    "vulnerability_index": "render_vulnerability_index_tab",
    "flood_model": "render_flood_model_tab",
    "wildfire_model": "render_wildfire_model_tab",
    "seismic_profiler": "render_seismic_profiler_tab",
    "land_use_ai": "render_land_use_ai_tab",
    "water_quality_ai": "render_water_quality_tab",
    "carbon_footprint": "render_carbon_footprint_tab",
    "disaster_resilience": "render_disaster_resilience_tab",
    "settlement_ai": "render_settlement_ai_tab",
    "agriculture_ai": "render_agriculture_ai_tab",
    "energy_potential": "render_energy_potential_tab",
    "geo_intelligence": "render_geo_intelligence_tab",
    "coastal_analysis": "render_coastal_analysis_tab",
    "urban_planning_ai": "render_urban_planning_tab",
    "emergency_response": "render_emergency_response_tab",
    "terrain_traversal": "render_terrain_traversal_tab",
    "noise_pollution": "render_noise_pollution_tab",
    "biodiversity_hotspot": "render_biodiversity_hotspot_tab",
    "logistics_ai": "render_logistics_ai_tab",
    "tourism_potential": "render_tourism_potential_tab",
    "air_quality_ai": "render_air_quality_ai_tab",
    "strategic_value": "render_strategic_value_tab",
    "contamination_ai": "render_contamination_tab",
    "population_density": "render_population_density_tab",
    "mineral_prospecting": "render_mineral_prospecting_tab",
    "archaeological_ai": "render_archaeological_ai_tab",
    "military_terrain": "render_military_terrain_tab",
    "health_geography": "render_health_geography_tab",
    "privacy_index": "render_privacy_index_tab",
    "survival_score": "render_survival_score_tab",
    "real_estate_ai": "render_real_estate_ai_tab",
    "forestry_ai": "render_forestry_ai_tab",
    "hydrology_ai": "render_hydrology_ai_tab",
    "geopolitical_ai": "render_geopolitical_ai_tab",
    "renewable_grid": "render_renewable_grid_tab",
    "soil_erosion_ai": "render_soil_erosion_ai_tab",
    "wildlife_corridor": "render_wildlife_corridor_tab",
    "infrastructure_age": "render_infrastructure_age_tab",
    "viewshed_ai": "render_viewshed_ai_tab",
    "unified_intelligence": "render_unified_intelligence_tab",
    "decision_matrix": "render_decision_matrix_tab",
    "proximity_scanner": "render_proximity_scanner_tab",
    "climate_adaptation": "render_climate_adaptation_tab",
    "food_security": "render_food_security_tab",
    "connectivity_score": "render_connectivity_score_tab",
    "cultural_heritage": "render_cultural_heritage_tab",
    "transportation_ai": "render_transportation_ai_tab",
    "demographic_profiler": "render_demographic_profiler_tab",
    "pollution_tracker": "render_pollution_tracker_tab",
    "shelter_analysis": "render_shelter_analysis_tab",
    "security_assessment": "render_security_assessment_tab",
    "geological_risk": "render_geological_risk_tab",
    "smart_zoning": "render_smart_zoning_tab",
    "climate_forecast": "render_climate_forecast_tab",
    "vegetation_index": "render_vegetation_index_tab",
    "boundary_intel": "render_boundary_intel_tab",
    "signal_coverage": "render_signal_coverage_tab",
    "terrain_mobility": "render_terrain_mobility_tab",
    "resource_mapping": "render_resource_mapping_tab",
    "threat_assessment": "render_threat_assessment_tab",
    "livability_score": "render_livability_score_tab",
    "elevation_profiler": "render_elevation_profiler_tab",
    "night_ops": "render_night_ops_tab",
    "seasonal_analysis": "render_seasonal_analysis_tab",
    "cross_domain_ai": "render_cross_domain_ai_tab",
    "soil_health_ai": "render_soil_health_ai_tab",
    "wind_analysis": "render_wind_analysis_tab",
    "solar_analysis": "render_solar_analysis_tab",
    "satellite_imagery": "render_satellite_imagery_tab",
    "water_security": "render_water_security_tab",
    "fire_weather": "render_fire_weather_tab",
    "infrastructure_scan": "render_infrastructure_scan_tab",
    "construction_ai": "render_construction_ai_tab",
    "grazing_potential": "render_grazing_potential_tab",
    "landing_zone": "render_landing_zone_tab",
    "expedition_planner": "render_expedition_planner_tab",
    "radio_propagation": "render_radio_propagation_tab",
    "evacuation_route": "render_evacuation_route_tab",
    "camp_site": "render_camp_site_tab",
    "ground_truth": "render_ground_truth_tab",
    "intelligence_briefing": "render_intelligence_briefing_tab",
    "fusion_console": "render_fusion_console",
}

# Module ID to import path mapping
MODULE_IMPORT_MAP = {
    # Core modules (always loaded)
    "analyzer": "src.analyzer",
    "ui": "src.ui",
    "project_manager": "src.project_manager",

    # Analysis & AI
    "open_buildings": "src.open_buildings_explorer",
    "remote_explorer": "src.remote_explorer",
    "map_catalog": "src.map_catalog",
    "zone_intel": "src.zone_intelligence",
    "deep_analysis": "src.deep_zone_analysis",
    "api_health": "src.api_health_dashboard",

    # Data Explorer
    "osm_explorer": "src.osm_explorer",
    "elevation": "src.elevation",
    "weather": "src.weather",
    "geocoder": "src.geocoder",
    "biodiversity": "src.biodiversity",
    "lidar_browser": "src.lidar_browser",
    "earthquake": "src.earthquake",
    "air_quality": "src.air_quality",
    "wildfires": "src.fire_tracker",
    "geology": "src.geology",
    "archaeology": "src.archaeology",
    "soil": "src.soil_explorer",
    "water": "src.water_explorer",
    "landuse": "src.landuse_explorer",
    "nasa_events": "src.nasa_events",
    "weather_radar": "src.weather_radar",
    "ocean": "src.ocean_explorer",
    "demographics": "src.world_demographics",
    "space_tracker": "src.space_tracker",
    "climate": "src.climate_monitor",
    "global_health": "src.global_health",
    "energy": "src.energy_explorer",

    # Thematic Maps
    "thematic": "src.thematic_maps",
    "historical": "src.historical_maps",
    "biogeography": "src.biogeography_maps",
    "world_data": "src.world_data_maps",
    "civilization": "src.civilization_maps",
    "realtime": "src.realtime_dashboard",
    "transport": "src.transport_maps",
    "urban": "src.urban_analytics",
    "disaster": "src.disaster_maps",
    "military": "src.military_maps",
    "linguistic": "src.linguistic_maps",
    "agriculture": "src.agriculture_maps",
    "astronomy": "src.astronomy_maps",
    "economics": "src.economics_maps",
    "technology": "src.technology_maps",
    "pollution": "src.pollution_maps",
    "maritime": "src.maritime_maps",
    "sports": "src.sports_maps",
    "architecture": "src.architecture_maps",
    "extreme_geo": "src.extreme_geography",
    "music_culture": "src.music_culture_maps",
    "pilgrimage": "src.pilgrimage_maps",
    "education": "src.education_maps",
    "migration": "src.migration_maps",
    "mythology": "src.mythology_maps",
    "cinema": "src.cinema_maps",
    "gastronomy": "src.gastronomy_maps",
    "crime_safety": "src.crime_safety_maps",
    "paranormal": "src.paranormal_maps",
    "medical": "src.medical_maps",
    "fashion": "src.fashion_maps",
    "literature": "src.literature_maps",
    "archaeology_deep": "src.archaeology_deep",
    "genetics": "src.genetics_maps",
    "animal_maps": "src.animal_maps",
    "cost_living": "src.cost_living_maps",
    "railway": "src.railway_maps",
    "climate_history": "src.climate_history_maps",
    "empires": "src.empires_maps",
    "exploration": "src.exploration_maps",
    "unesco": "src.unesco_maps",
    "borders": "src.borders_conflicts_maps",
    "volcanoes": "src.volcano_maps",
    "pandemic": "src.pandemic_maps",
    "shipwreck": "src.shipwreck_maps",
    "airport": "src.airport_maps",
    "nuclear": "src.nuclear_maps",
    "deserts": "src.desert_maps",
    "wine": "src.wine_maps",
    "islands": "src.island_maps",
    "bridge": "src.bridge_maps",
    "population": "src.population_maps",
    "caves": "src.cave_maps",
    "waterfalls": "src.waterfall_maps",
    "lighthouse": "src.lighthouse_maps",
    "mining": "src.mining_maps",
    "glaciers": "src.glacier_maps",
    "mountains": "src.mountain_maps",
    "religion": "src.religion_maps",
    "renewable": "src.renewable_maps",
    "composite": "src.composite_maps",
    "trade_routes": "src.trade_routes_maps",
    "crypto": "src.crypto_maps",
    "prison": "src.prison_maps",
    "tattoo": "src.tattoo_maps",
    "treasure": "src.treasure_maps",
    "fjords": "src.fjord_maps",
    "festival": "src.festival_maps",
    "ruins": "src.ruins_maps",
    "calendar": "src.calendar_maps",
    "cryptid": "src.cryptid_maps",
    "street_art": "src.street_art_maps",
    "underwater": "src.underwater_maps",
    "botanical": "src.botanical_maps",
    "amusement": "src.amusement_maps",
    "cuisine": "src.cuisine_maps",
    "myth_locations": "src.myth_locations_maps",
    "writing": "src.writing_maps",
    "trad_med": "src.trad_medicine_maps",
    "space": "src.space_maps",
    "language": "src.language_maps",
    "haunted": "src.haunted_maps",
    "martial_arts": "src.martial_arts_maps",
    "games": "src.games_maps",
    "perfume": "src.perfume_maps",
    "toy": "src.toy_maps",
    "conspiracy": "src.conspiracy_maps",
    "clock": "src.clock_maps",
    "textile": "src.textile_maps",
    "dance": "src.dance_maps",
    "museum": "src.museum_maps",
    "opera": "src.opera_maps",
    "cemetery": "src.cemetery_maps",
    "garden": "src.garden_maps",
    "fortress": "src.fortress_maps",
    "market": "src.market_maps",
    "spa": "src.spa_maps",
    "coin": "src.coin_maps",
    "library": "src.library_maps",
    "instrument": "src.instrument_maps",
    "photography": "src.photography_maps",
    "zodiac": "src.zodiac_maps",
    "jewelry": "src.jewelry_maps",
    "calligraphy": "src.calligraphy_maps",
    "chocolate": "src.chocolate_maps",
    "pottery": "src.pottery_maps",
    "sculpture": "src.sculpture_maps",
    "circus": "src.circus_maps",
    "ancient_weapons": "src.ancient_weapons_maps",
    "horse": "src.horse_maps",
    "tea": "src.tea_maps",
    "robot": "src.robot_maps",
    "rice": "src.rice_maps",
    "corn": "src.corn_maps",
    "wheat": "src.wheat_maps",
    "potato": "src.potato_maps",
    "soy": "src.soy_maps",
    "cotton": "src.cotton_maps",
    "submarine": "src.submarine_maps",
    "silk_road": "src.silk_road_maps",
    "marathon": "src.marathon_maps",
    "pirate": "src.pirate_maps",
    "dragon": "src.dragon_maps",
    "candy": "src.candy_maps",
    "pasta": "src.pasta_maps",
    "carnival": "src.carnival_maps",
    "gemstone": "src.gemstone_maps",
    "volcano_deep": "src.volcano_deep_maps",
    "dinosaur": "src.dinosaur_maps",
    "origami": "src.origami_maps",
    "ancient": "src.ancient_maps",
    "ice_cream": "src.ice_cream_maps",
    "train_journey": "src.train_journey_maps",
    "telescope": "src.telescope_maps",
    "skyscraper": "src.skyscraper_maps",
    "coral_reef": "src.coral_reef_maps",
    "street_food": "src.street_food_maps",
    "waterpark": "src.waterpark_maps",
    "mythology_deep": "src.mythology_deep_maps",
    "global_realtime": "src.global_realtime",
    "global_dashboard": "src.global_dashboard_realtime",
    "cheese": "src.cheese_maps",
    "coffee": "src.coffee_maps",
    "spice": "src.spice_maps",
    "beer": "src.beer_maps",
    "honey": "src.honey_maps",
    "salt": "src.salt_maps",
    "mask": "src.mask_maps",
    "bread": "src.bread_maps",
    "glass": "src.glass_maps",
    "olive": "src.olive_maps",
    "bamboo": "src.bamboo_maps",
    "volcano_live": "src.volcano_live_maps",
    "waterways": "src.waterway_maps",
    "medieval": "src.medieval_maps",
    "indigenous": "src.indigenous_maps",
    "hidden_structures": "src.hidden_structures_maps",
    "biodiv_global": "src.biodiversity_global_maps",  # Function: render_biodiversity_global_maps_tab
    "isolated_buildings": "src.isolated_buildings_maps",

    # New modules (v2)
    "compare_locations": "src.compare_locations",
    "route_analysis": "src.route_analysis",
    "predictive_risk": "src.predictive_risk",
    "timeline": "src.timeline_analysis",
    "night_vision": "src.night_vision",
    "terrain_3d": "src.terrain_3d",
    "report_gen": "src.report_generator",
    "ocean_proximity": "src.ocean_proximity",
    "climate_zone": "src.climate_zone",
    "scenario_simulator": "src.scenario_simulator",
    "mining_suitability": "src.mining_suitability",
    "ai_scoring": "src.ai_scoring",
    "smart_insights": "src.smart_insights",
    "environmental_dna": "src.environmental_dna",
    "suitability_analyzer": "src.suitability_analyzer",
    "anomaly_detector": "src.anomaly_detector",
    "threat_matrix": "src.threat_matrix",
    "pattern_recognizer": "src.pattern_recognizer",
    "mission_planner": "src.mission_planner",
    "correlation_engine": "src.correlation_engine",
    "change_detector": "src.change_detector",
    "strategic_report": "src.strategic_report",
    "terrain_classifier": "src.terrain_classifier",
    "water_intelligence": "src.water_intelligence",
    "geo_profiler": "src.geo_profiler",
    "site_ranker": "src.site_ranker",
    "network_analysis": "src.network_analysis",
    "multi_hazard": "src.multi_hazard",
    "data_fusion": "src.data_fusion",
    "climate_dashboard": "src.climate_dashboard",
    "resource_scanner": "src.resource_scanner",
    "infra_density": "src.population_density",
    "ecosystem_health": "src.ecosystem_health",
    "land_capability": "src.land_capability",
    "accessibility_mapper": "src.accessibility_mapper",
    "climate_risk_ai": "src.climate_risk_ai",
    "resource_potential": "src.resource_potential",
    "habitat_analyzer": "src.habitat_analyzer",
    "soil_intelligence": "src.soil_intelligence",
    "microclimate_ai": "src.microclimate_ai",
    "environmental_score": "src.environmental_score",
    "vulnerability_index": "src.vulnerability_index",
    "flood_model": "src.flood_model",
    "wildfire_model": "src.wildfire_model",
    "seismic_profiler": "src.seismic_profiler",
    "land_use_ai": "src.land_use_ai",
    "water_quality_ai": "src.water_quality_ai",
    "carbon_footprint": "src.carbon_footprint",
    "disaster_resilience": "src.disaster_resilience",
    "settlement_ai": "src.settlement_ai",
    "agriculture_ai": "src.agriculture_ai",
    "energy_potential": "src.energy_potential",
    "geo_intelligence": "src.geo_intelligence",
    "coastal_analysis": "src.coastal_analysis",
    "urban_planning_ai": "src.urban_planning_ai",
    "emergency_response": "src.emergency_response",
    "terrain_traversal": "src.terrain_traversal",
    "noise_pollution": "src.noise_pollution",
    "biodiversity_hotspot": "src.biodiversity_hotspot",
    "logistics_ai": "src.logistics_ai",
    "tourism_potential": "src.tourism_potential",
    "air_quality_ai": "src.air_quality_ai",
    "strategic_value": "src.strategic_value",
    "contamination_ai": "src.contamination_ai",
    "population_density": "src.population_density",
    "mineral_prospecting": "src.mineral_prospecting",
    "archaeological_ai": "src.archaeological_ai",
    "military_terrain": "src.military_terrain",
    "health_geography": "src.health_geography",
    "privacy_index": "src.privacy_index",
    "survival_score": "src.survival_score",
    "real_estate_ai": "src.real_estate_ai",
    "forestry_ai": "src.forestry_ai",
    "hydrology_ai": "src.hydrology_ai",
    "geopolitical_ai": "src.geopolitical_ai",
    "renewable_grid": "src.renewable_grid",
    "soil_erosion_ai": "src.soil_erosion_ai",
    "wildlife_corridor": "src.wildlife_corridor",
    "infrastructure_age": "src.infrastructure_age",
    "viewshed_ai": "src.viewshed_ai",
    "unified_intelligence": "src.unified_intelligence",
    "decision_matrix": "src.decision_matrix",
    "proximity_scanner": "src.proximity_scanner",
    "climate_adaptation": "src.climate_adaptation",
    "food_security": "src.food_security",
    "connectivity_score": "src.connectivity_score",
    "cultural_heritage": "src.cultural_heritage",
    "transportation_ai": "src.transportation_ai",
    "demographic_profiler": "src.demographic_profiler",
    "pollution_tracker": "src.pollution_tracker",
    "shelter_analysis": "src.shelter_analysis",
    "security_assessment": "src.security_assessment",
    "geological_risk": "src.geological_risk",
    "smart_zoning": "src.smart_zoning",
    "climate_forecast": "src.climate_forecast",
    "vegetation_index": "src.vegetation_index",
    "boundary_intel": "src.boundary_intel",
    "signal_coverage": "src.signal_coverage",
    "terrain_mobility": "src.terrain_mobility",
    "resource_mapping": "src.resource_mapping",
    "threat_assessment": "src.threat_assessment",
    "livability_score": "src.livability_score",
    "elevation_profiler": "src.elevation_profiler",
    "night_ops": "src.night_ops",
    "seasonal_analysis": "src.seasonal_analysis",
    "cross_domain_ai": "src.cross_domain_ai",
    "soil_health_ai": "src.soil_health_ai",
    "wind_analysis": "src.wind_analysis",
    "solar_analysis": "src.solar_analysis",
    "satellite_imagery": "src.satellite_imagery",
    "water_security": "src.water_security",
    "fire_weather": "src.fire_weather",
    "infrastructure_scan": "src.infrastructure_scan",
    "construction_ai": "src.construction_ai",
    "grazing_potential": "src.grazing_potential",
    "landing_zone": "src.landing_zone",
    "expedition_planner": "src.expedition_planner",
    "radio_propagation": "src.radio_propagation",
    "evacuation_route": "src.evacuation_route",
    "camp_site": "src.camp_site",
    "ground_truth": "src.ground_truth",
    "intelligence_briefing": "src.intelligence_briefing",
    "fusion_console": "src.fusion_console",
}


def load_module_render_function(module_id: str, render_function_name: Optional[str] = None) -> Optional[Callable]:
    """
    Dynamically load a module's render function on demand.

    Args:
        module_id: Module identifier (e.g., "remote_explorer")
        render_function_name: Name of the render function (auto-detected if None)

    Returns:
        The render function or None if loading fails

    Examples:
        >>> render_fn = load_module_render_function("remote_explorer")
        >>> render_fn()  # Calls render_remote_explorer_tab()
    """
    # Check cache first
    cache_key = f"{module_id}:{render_function_name or 'default'}"
    if cache_key in _render_function_cache:
        return _render_function_cache[cache_key]

    # Get module import path
    if module_id not in MODULE_IMPORT_MAP:
        st.error(f"⚠️ Unknown module: {module_id}")
        return None

    module_path = MODULE_IMPORT_MAP[module_id]

    # Auto-detect render function name if not provided
    if render_function_name is None:
        # Check if there's a custom function name for this module
        if module_id in CUSTOM_FUNCTION_NAMES:
            render_function_name = CUSTOM_FUNCTION_NAMES[module_id]
        else:
            # Convert module_id to function name: "remote_explorer" -> "render_remote_explorer_tab"
            render_function_name = f"render_{module_id}_tab"

    try:
        # Dynamic import
        module = importlib.import_module(module_path)

        # Get render function
        if not hasattr(module, render_function_name):
            st.error(f"⚠️ Function {render_function_name} not found in {module_path}")
            return None

        render_function = getattr(module, render_function_name)

        # Cache it
        _render_function_cache[cache_key] = render_function

        return render_function

    except ImportError as e:
        st.error(f"⚠️ Failed to import {module_path}: {e}")
        return None
    except Exception as e:
        st.error(f"⚠️ Error loading {module_id}: {e}")
        return None


def preload_core_modules():
    """
    Preload essential modules that are needed on every startup.
    Called once during app initialization.
    """
    core_modules = ["analyzer", "ui", "project_manager"]

    for module_id in core_modules:
        if module_id in MODULE_IMPORT_MAP:
            try:
                importlib.import_module(MODULE_IMPORT_MAP[module_id])
            except Exception as e:
                st.warning(f"⚠️ Could not preload {module_id}: {e}")


def get_loaded_modules_count() -> int:
    """Return the number of modules currently loaded in memory."""
    return len(_render_function_cache)


def clear_module_cache():
    """Clear the module cache. Useful for development/debugging."""
    global _render_function_cache
    _render_function_cache.clear()


# Convenience wrapper for common patterns
def lazy_render(module_id: str, render_function_name: Optional[str] = None):
    """
    Lazy-load and execute a module's render function.

    Usage in app.py:
        lazy_render("remote_explorer")  # Loads and calls render_remote_explorer_tab()
    """
    render_fn = load_module_render_function(module_id, render_function_name)
    if render_fn:
        try:
            render_fn()
        except Exception as e:
            st.error(f"⚠️ Error rendering {module_id}: {e}")
            import traceback
            st.code(traceback.format_exc())
